# Generated by Django 4.2.10 on 2024-03-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('mobile', models.IntegerField(max_length=10, null=True)),
                ('date', models.DateField(null=True)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
