# Generated by Django 4.2.10 on 2024-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
