# Generated by Django 4.2.10 on 2024-03-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_appointments_age_alter_appointments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
