# Generated by Django 4.2.10 on 2024-03-11 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0007_alter_appointments_date_alter_appointments_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='user_apointment',
            field=models.ForeignKey(db_column='userid', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
