# Generated by Django 4.2.10 on 2024-03-11 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0008_appointments_user_apointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='user_apointment',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
